cmd_/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o := arm-hisiv300-linux-gcc -Wp,-MD,/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/.isp_acm_lut.o.d  -nostdinc -isystem /opt/hisi-linux/x86-arm/arm-hisiv300-linux/bin/../lib/gcc/arm-hisiv300-linux-uclibcgnueabi/4.8.3/include -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/osdrv/opensource/kernel/linux-3.4.y/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include /home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/osdrv/opensource/kernel/linux-3.4.y/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-hi3518ev200/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -fno-aggressive-loop-optimizations -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=5 -march=armv5te -mtune=arm9tdmi -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -Wall -DVER_X=1 -DVER_Y=0 -DVER_Z=0 -DVER_P=0 -DVER_B=10 -D ENABLE_JPEGEDCF -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/include -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/code/mkp/include -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/include -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/code/arch/hi3518e/include -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/code/mkp_inc -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/vreg -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/vreg/arch/hi3518e -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/include -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/extdrv/i2c -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/extdrv/hi_i2c -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/extdrv/ssp-sony -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/extdrv/i2c -I/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/extdrv/hi_i2c -D ENABLE_JPEGEDCF -DHI_XXXX -DHI_GPIO_XXX -DHI_RELEASE  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(isp_acm_lut)"  -D"KBUILD_MODNAME=KBUILD_STR(hi3518e_isp)" -c -o /home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o /home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.c

source_/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o := /home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.c

deps_/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o := \
  /home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/include/hi_type.h \

/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o: $(deps_/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o)

$(deps_/home/aston/sambashare/Hi3518E_SDK_V1.0.3.0/mpp/component/isp/firmware/drv/isp_acm_lut.o):
